Fail if doxygen, pdflatex, or bibtex are missing.
git-svn-id: https://svn.aspect.dealii.org/trunk/aspect@478 244a8438-9d6d-46c2-a098-b74c898f6b90

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -11,6 +11,12 @@ aspect-files    = $(shell echo ../include/aspect/*.h ../include/aspect/*/*h modu
 all: aspect.tag manual.pdf
 
 aspect.tag: $(aspect-files) options.dox
+	@if test ! -x "`which doxygen`" ; then \
+	  echo "-----------------------------------------" ; \
+	  echo "Can't find 'doxygen'." ; \
+	  echo "-----------------------------------------" ; \
+	  false ; \
+	 fi
 	@echo "=====aspect=================== Generating documentation"
 	@echo '@INCLUDE = options.dox'                                > aspect.dox
 	@echo 'INCLUDE_PATH           = $D/include/deal.II'          >> aspect.dox
@@ -18,15 +24,22 @@ aspect.tag: $(aspect-files) options.dox
 	@echo 'INPUT = $(aspect-files)'                              >> aspect.dox
 	@echo 'HTML_OUTPUT      = doxygen'                           >> aspect.dox
 	@echo 'GENERATE_TAGFILE = $@'                                >> aspect.dox
-	@doxygen aspect.dox
+	@doxygen aspect.dox || echo "Running doxygen to generate documentation failed."
 
 manual.pdf: manual/manual.tex manual/manual.bib
-	@cd manual ; \
+	@if test -x "`which pdflatex`" -a -x "`which bibtex`" ; then \
+	   (cd manual ; \
 		pdflatex manual.tex ; \
 		bibtex manual       ; \
 		pdflatex manual.tex ; \
-		pdflatex manual.tex
-	@mv manual/manual.pdf .
+		pdflatex manual.tex) ; \
+	   mv manual/manual.pdf . ; \
+         else \
+	  echo "-----------------------------------------" ; \
+	  echo "Can't find either 'pdflatex' or 'bibtex'." ; \
+	  echo "-----------------------------------------" ; \
+	  false ; \
+	 fi
 
 clean:
 	-rm -f aspect.dox aspect.tag
